# Generated by Django 5.2.dev20241108121644 on 2026-03-20 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('genre', models.CharField(choices=[('jazz', 'Jazz'), ('pop', 'Pop'), ('electronic', 'Electronic'), ('rock', 'Rock')], max_length=20)),
                ('mood', models.CharField(blank=True, default='', max_length=100)),
                ('occasion', models.CharField(blank=True, default='', max_length=100)),
                ('story', models.TextField(max_length=2000)),
                ('lyrics', models.CharField(blank=True, default='', max_length=5000)),
                ('language', models.CharField(blank=True, default='English', max_length=50)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('complete', 'Complete'), ('fail', 'Fail')], default='generating', max_length=15)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-created_at'],
            },
        ),
    ]
