# Generated by Django 5.2.13 on 2026-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('jazz', 'Jazz'), ('pop', 'Pop'), ('electronic', 'Electronic'), ('rock', 'Rock'), ('hip_hop', 'Hip-Hop'), ('rnb', 'R&B'), ('classical', 'Classical'), ('country', 'Country'), ('blues', 'Blues'), ('reggae', 'Reggae'), ('metal', 'Metal'), ('indie', 'Indie'), ('folk', 'Folk')], max_length=20),
        ),
    ]
